Load Pre-Trained Models:

In [1]:
!pip install tensorflow    #ML Package
from tensorflow.keras.applications import ResNet50
from transformers import pipeline

model = ResNet50(weights='imagenet', include_top=False, pooling='avg')
caption_generator = pipeline("image-to-text", model="nlpconnect/vit-gpt2-image-captioning")

94765736/94765736 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/4.61k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/982M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/241 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/120 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


preprocessor_config.json:   0%|          | 0.00/228 [00:00<?, ?B/s]

Image Upload and Display

In [2]:
!pip install opencv-python
import cv2
from google.colab.patches import cv2_imshow

def get_image_path():
  from google.colab import files
  uploaded = files.upload()
  for filename in uploaded.keys():
    image_path = filename
    return image_path
image_path = get_image_path()
image = cv2.imread(image_path)
print(image) #cv2_imshow(image)

Saving Screenshot 2024-10-28 183143.png to Screenshot 2024-10-28 183143.png
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[163 163 163]
  [163 163 163]
  [163 163 163]
  ...
  [163 163 163]
  [163 163 163]
  [163 163 163]]

 [[161 161 161]
  [161 161 161]
  [161 161 161]
  ...
  [161 161 161]
  [161 161 161]
  [161 161 161]]

 [[159 159 159]
  [159 159 159]
  [159 159 159]
  ...
  [159 159 159]
  [159 159 159]
  [159 159 159]]]


Caption Generation

In [3]:
!pip install Pillow
from PIL import Image
import numpy as np
from keras.applications.resnet50 import preprocess_input #Import preprocess_input

if image_path:
    image_np = np.array(image) # PIL  to NumPy
    image_np = cv2.cvtColor(image_np, cv2.COLOR_BGR2RGB)  #Convert to RGB
    image = Image.fromarray(image_np)  #Convert back to PIL Image
    image = image.resize((224, 224))
    # image_array = np.array(image) #Convert PIL Image to NumPy array for preprocessing is not needed
    # image_array = preprocess_input(image_array) #Preprocess the image array is not needed
    caption = caption_generator(image)[0]["generated_text"] #Pass PIL Image to caption generator
    print("Caption:", caption)
else:
    print("No image uploaded.")

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1258: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.
You may ignore this warning if your `pad_token_id` (50256) is identical to the `bos_token_id` (50256), `eos_token_id` (50256), or the `sep_token_id` (None), and your input is not padded.


Caption: a collage of various pictures of a computer 
